# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  database: 'dveLSbKzSf5ye0nHoO9IyXQp_fzTRMNM'
  redis: 'HnoOdjg-9m0Bi1MPfDL4HvyG7dNs0YY1'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'AtdGiyqim0Stu3QTBqVeYNYdlqVj88_j'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  database: 'SklgN_2Yzsfs0XoVLZ2-rT4kNOFT0q5i'
  serviceSecret: 'cjUyukufmbuxkPok2vaaZ1djsVQaobg7'

# Passwords used in production mode.
production:
  database: 'LjE1samW54I_Z2LfB_kj4jYkxehjnnag'
  serviceSecret: 'JwLgwDhQgNrhQUbDFcVARJzJJ9Nwu_DL'
